<?php namespace Epigra\TrGeoZones\Database\Seeds;

use Illuminate\Database\Seeder;
use Epigra\TrGeoZones\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$countries = array(
            array('iso_code'=>'TR', 'name'=>'Türkiye'),
            array('iso_code'=>'AF', 'name'=>'Afganistan'),
            array('iso_code'=>'AX', 'name'=>'Aland Adaları'),
            array('iso_code'=>'DE', 'name'=>'Almanya'),
            array('iso_code'=>'US', 'name'=>'Amerika Birleşik Devletleri'),
            array('iso_code'=>'UM', 'name'=>'Amerika Birleşik Devletleri Küçük Dış Adaları'),
            array('iso_code'=>'AS', 'name'=>'Amerikan Samoası'),
    	    array('iso_code'=>'VI', 'name'=>'ABD Virgin Adaları'),
    	    array('iso_code'=>'AD', 'name'=>'Andorra'),
    	    array('iso_code'=>'AO', 'name'=>'Angola'),
    	    array('iso_code'=>'AI', 'name'=>'Anguilla'),
    	    array('iso_code'=>'AQ', 'name'=>'Antarktika'),
    	    array('iso_code'=>'AG', 'name'=>'Antigua ve Barbuda'),
    	    array('iso_code'=>'AR', 'name'=>'Arjantin'),
    	    array('iso_code'=>'AL', 'name'=>'Arnavutluk'),
    	    array('iso_code'=>'AW', 'name'=>'Aruba'),
    	    array('iso_code'=>'AU', 'name'=>'Avustralya'),
    	    array('iso_code'=>'AT', 'name'=>'Avusturya'),
    	    array('iso_code'=>'AZ', 'name'=>'Azerbaycan'),
    	    array('iso_code'=>'BS', 'name'=>'Bahamalar'),
    	    array('iso_code'=>'BH', 'name'=>'Bahreyn'),
    	    array('iso_code'=>'BD', 'name'=>'Bangladeş'),
    	    array('iso_code'=>'BB', 'name'=>'Barbados'),
    	    array('iso_code'=>'EH', 'name'=>'Batı Sahara'),
    	    array('iso_code'=>'BZ', 'name'=>'Belize'),
    	    array('iso_code'=>'BE', 'name'=>'Belçika'),
    	    array('iso_code'=>'BJ', 'name'=>'Benin'),
    	    array('iso_code'=>'BM', 'name'=>'Bermuda'),
    	    array('iso_code'=>'BY', 'name'=>'Beyaz Rusya'),
    	    array('iso_code'=>'BT', 'name'=>'Bhutan'),
    	    array('iso_code'=>'ZZ', 'name'=>'Bilinmeyen veya Geçersiz Bölge'),
    	    array('iso_code'=>'AE', 'name'=>'Birleşik Arap Emirlikleri'),
    	    array('iso_code'=>'GB', 'name'=>'Birleşik Krallık'),
    	    array('iso_code'=>'BO', 'name'=>'Bolivya'),
    	    array('iso_code'=>'BA', 'name'=>'Bosna Hersek'),
    	    array('iso_code'=>'BW', 'name'=>'Botsvana'),
    	    array('iso_code'=>'BV', 'name'=>'Bouvet Adası'),
    	    array('iso_code'=>'BR', 'name'=>'Brezilya'),
    	    array('iso_code'=>'BN', 'name'=>'Brunei'),
    	    array('iso_code'=>'BG', 'name'=>'Bulgaristan'),
    	    array('iso_code'=>'BF', 'name'=>'Burkina Faso'),
    	    array('iso_code'=>'BI', 'name'=>'Burundi'),
    	    array('iso_code'=>'CV', 'name'=>'Cape Verde'),
    	    array('iso_code'=>'KY', 'name'=>'Cayman Adaları'),
    	    array('iso_code'=>'GI', 'name'=>'Cebelitarık'),
    	    array('iso_code'=>'DZ', 'name'=>'Cezayir'),
    	    array('iso_code'=>'CX', 'name'=>'Christmas Adası'),
    	    array('iso_code'=>'DJ', 'name'=>'Cibuti'),
    	    array('iso_code'=>'CC', 'name'=>'Cocos Adaları'),
    	    array('iso_code'=>'CK', 'name'=>'Cook Adaları'),
    	    array('iso_code'=>'DK', 'name'=>'Danimarka'),
    	    array('iso_code'=>'DO', 'name'=>'Dominik Cumhuriyeti'),
    	    array('iso_code'=>'DM', 'name'=>'Dominika'),
    	    array('iso_code'=>'TL', 'name'=>'Doğu Timor'),
    	    array('iso_code'=>'EC', 'name'=>'Ekvador'),
    	    array('iso_code'=>'GQ', 'name'=>'Ekvator Ginesi'),
    	    array('iso_code'=>'SV', 'name'=>'El Salvador'),
    	    array('iso_code'=>'ID', 'name'=>'Endonezya'),
    	    array('iso_code'=>'ER', 'name'=>'Eritre'),
    	    array('iso_code'=>'AM', 'name'=>'Ermenistan'),
    	    array('iso_code'=>'EE', 'name'=>'Estonya'),
    	    array('iso_code'=>'ET', 'name'=>'Etiyopya'),
    	    array('iso_code'=>'FK', 'name'=>'Falkland Adaları'),
    	    array('iso_code'=>'FO', 'name'=>'Faroe Adaları'),
    	    array('iso_code'=>'MA', 'name'=>'Fas'),
    	    array('iso_code'=>'FJ', 'name'=>'Fiji'),
    	    array('iso_code'=>'CI', 'name'=>'Fildişi Sahili'),
    	    array('iso_code'=>'PH', 'name'=>'Filipinler'),
    	    array('iso_code'=>'PS', 'name'=>'Filistin Bölgesi'),
    	    array('iso_code'=>'FI', 'name'=>'Finlandiya'),
    	    array('iso_code'=>'FR', 'name'=>'Fransa'),
    	    array('iso_code'=>'GF', 'name'=>'Fransız Guyanası'),
    	    array('iso_code'=>'TF', 'name'=>'Fransız Güney Bölgeleri'),
    	    array('iso_code'=>'PF', 'name'=>'Fransız Polinezyası'),
    	    array('iso_code'=>'GA', 'name'=>'Gabon'),
    	    array('iso_code'=>'GM', 'name'=>'Gambiya'),
    	    array('iso_code'=>'GH', 'name'=>'Gana'),
    	    array('iso_code'=>'GN', 'name'=>'Gine'),
    	    array('iso_code'=>'GW', 'name'=>'Gine-Bissau'),
    	    array('iso_code'=>'GD', 'name'=>'Grenada'),
    	    array('iso_code'=>'GL', 'name'=>'Grönland'),
    	    array('iso_code'=>'GP', 'name'=>'Guadeloupe'),
    	    array('iso_code'=>'GU', 'name'=>'Guam'),
    	    array('iso_code'=>'GT', 'name'=>'Guatemala'),
    	    array('iso_code'=>'GG', 'name'=>'Guernsey'),
    	    array('iso_code'=>'GY', 'name'=>'Guyana'),
    	    array('iso_code'=>'ZA', 'name'=>'Güney Afrika'),
    	    array('iso_code'=>'GS', 'name'=>'Güney Georgia ve Güney Sandwich Adaları'),
    	    array('iso_code'=>'KR', 'name'=>'Güney Kore'),
    	    array('iso_code'=>'CY', 'name'=>'Güney Kıbrıs Rum Kesimi'),
    	    array('iso_code'=>'GE', 'name'=>'Gürcistan'),
    	    array('iso_code'=>'HT', 'name'=>'Haiti'),
    	    array('iso_code'=>'HM', 'name'=>'Heard Adası ve McDonald Adaları'),
    	    array('iso_code'=>'IN', 'name'=>'Hindistan'),
    	    array('iso_code'=>'IO', 'name'=>'Hint Okyanusu İngiliz Bölgesi'),
    	    array('iso_code'=>'NL', 'name'=>'Hollanda'),
    	    array('iso_code'=>'AN', 'name'=>'Hollanda Antilleri'),
    	    array('iso_code'=>'HN', 'name'=>'Honduras'),
    	    array('iso_code'=>'HK', 'name'=>'Hong Kong SAR - Çin'),
    	    array('iso_code'=>'HR', 'name'=>'Hırvatistan'),
    	    array('iso_code'=>'IQ', 'name'=>'Irak'),
    	    array('iso_code'=>'JM', 'name'=>'Jamaika'),
    	    array('iso_code'=>'JP', 'name'=>'Japonya'),
    	    array('iso_code'=>'JE', 'name'=>'Jersey'),
    	    array('iso_code'=>'KH', 'name'=>'Kamboçya'),
    	    array('iso_code'=>'CM', 'name'=>'Kamerun'),
    	    array('iso_code'=>'CA', 'name'=>'Kanada'),
    	    array('iso_code'=>'ME', 'name'=>'Karadağ'),
    	    array('iso_code'=>'QA', 'name'=>'Katar'),
    	    array('iso_code'=>'KZ', 'name'=>'Kazakistan'),
    	    array('iso_code'=>'KE', 'name'=>'Kenya'),
    	    array('iso_code'=>'KI', 'name'=>'Kiribati'),
    	    array('iso_code'=>'CO', 'name'=>'Kolombiya'),
    	    array('iso_code'=>'KM', 'name'=>'Komorlar'),
    	    array('iso_code'=>'CG', 'name'=>'Kongo - Brazavil'),
    	    array('iso_code'=>'CD', 'name'=>'Kongo - Kinşasa'),
    	    array('iso_code'=>'CR', 'name'=>'Kosta Rika'),
    	    array('iso_code'=>'KW', 'name'=>'Kuveyt'),
    	    array('iso_code'=>'KP', 'name'=>'Kuzey Kore'),
    	    array('iso_code'=>'MP', 'name'=>'Kuzey Mariana Adaları'),
    	    array('iso_code'=>'KK', 'name'=>'Kuzey Kıbrıs Türk Cumhuriyeti'),
    	    array('iso_code'=>'CU', 'name'=>'Küba'),
    	    array('iso_code'=>'KG', 'name'=>'Kırgızistan'),
    	    array('iso_code'=>'LA', 'name'=>'Laos'),
    	    array('iso_code'=>'LS', 'name'=>'Lesotho'),
    	    array('iso_code'=>'LV', 'name'=>'Letonya'),
    	    array('iso_code'=>'LR', 'name'=>'Liberya'),
    	    array('iso_code'=>'LY', 'name'=>'Libya'),
    	    array('iso_code'=>'LI', 'name'=>'Liechtenstein'),
    	    array('iso_code'=>'LT', 'name'=>'Litvanya'),
    	    array('iso_code'=>'LB', 'name'=>'Lübnan'),
    	    array('iso_code'=>'LU', 'name'=>'Lüksemburg'),
    	    array('iso_code'=>'HU', 'name'=>'Macaristan'),
    	    array('iso_code'=>'MG', 'name'=>'Madagaskar'),
    	    array('iso_code'=>'MO', 'name'=>'Makao S.A.R. Çin'),
    	    array('iso_code'=>'MK', 'name'=>'Makedonya'),
    	    array('iso_code'=>'MW', 'name'=>'Malavi'),
    	    array('iso_code'=>'MV', 'name'=>'Maldivler'),
    	    array('iso_code'=>'MY', 'name'=>'Malezya'),
    	    array('iso_code'=>'ML', 'name'=>'Mali'),
    	    array('iso_code'=>'MT', 'name'=>'Malta'),
    	    array('iso_code'=>'IM', 'name'=>'Man Adası'),
    	    array('iso_code'=>'MH', 'name'=>'Marshall Adaları'),
    	    array('iso_code'=>'MQ', 'name'=>'Martinik'),
    	    array('iso_code'=>'MU', 'name'=>'Mauritius'),
    	    array('iso_code'=>'YT', 'name'=>'Mayotte'),
    	    array('iso_code'=>'MX', 'name'=>'Meksika'),
    	    array('iso_code'=>'FM', 'name'=>'Mikronezya Federal Eyaletleri'),
    	    array('iso_code'=>'MD', 'name'=>'Moldova'),
    	    array('iso_code'=>'MC', 'name'=>'Monako'),
    	    array('iso_code'=>'MS', 'name'=>'Montserrat'),
    	    array('iso_code'=>'MR', 'name'=>'Moritanya'),
    	    array('iso_code'=>'MZ', 'name'=>'Mozambik'),
    	    array('iso_code'=>'MN', 'name'=>'Moğolistan'),
    	    array('iso_code'=>'MM', 'name'=>'Myanmar'),
    	    array('iso_code'=>'EG', 'name'=>'Mısır'),
    	    array('iso_code'=>'NA', 'name'=>'Namibya'),
    	    array('iso_code'=>'NR', 'name'=>'Nauru'),
    	    array('iso_code'=>'NP', 'name'=>'Nepal'),
    	    array('iso_code'=>'NE', 'name'=>'Nijer'),
    	    array('iso_code'=>'NG', 'name'=>'Nijerya'),
    	    array('iso_code'=>'NI', 'name'=>'Nikaragua'),
    	    array('iso_code'=>'NU', 'name'=>'Niue'),
    	    array('iso_code'=>'NF', 'name'=>'Norfolk Adası'),
    	    array('iso_code'=>'NO', 'name'=>'Norveç'),
    	    array('iso_code'=>'CF', 'name'=>'Orta Afrika Cumhuriyeti'),
    	    array('iso_code'=>'PK', 'name'=>'Pakistan'),
    	    array('iso_code'=>'PW', 'name'=>'Palau'),
    	    array('iso_code'=>'PA', 'name'=>'Panama'),
    	    array('iso_code'=>'PG', 'name'=>'Papua Yeni Gine'),
    	    array('iso_code'=>'PY', 'name'=>'Paraguay'),
    	    array('iso_code'=>'PE', 'name'=>'Peru'),
    	    array('iso_code'=>'PN', 'name'=>'Pitcairn'),
    	    array('iso_code'=>'PL', 'name'=>'Polonya'),
    	    array('iso_code'=>'PT', 'name'=>'Portekiz'),
    	    array('iso_code'=>'PR', 'name'=>'Porto Riko'),
    	    array('iso_code'=>'RE', 'name'=>'Reunion'),
    	    array('iso_code'=>'RO', 'name'=>'Romanya'),
    	    array('iso_code'=>'RW', 'name'=>'Ruanda'),
    	    array('iso_code'=>'RU', 'name'=>'Rusya Federasyonu'),
    	    array('iso_code'=>'BL', 'name'=>'Saint Barthelemy'),
    	    array('iso_code'=>'SH', 'name'=>'Saint Helena'),
    	    array('iso_code'=>'KN', 'name'=>'Saint Kitts ve Nevis'),
    	    array('iso_code'=>'LC', 'name'=>'Saint Lucia'),
    	    array('iso_code'=>'MF', 'name'=>'Saint Martin'),
    	    array('iso_code'=>'PM', 'name'=>'Saint Pierre ve Miquelon'),
    	    array('iso_code'=>'VC', 'name'=>'Saint Vincent ve Grenadinler'),
    	    array('iso_code'=>'WS', 'name'=>'Samoa'),
    	    array('iso_code'=>'SM', 'name'=>'San Marino'),
    	    array('iso_code'=>'ST', 'name'=>'Sao Tome ve Principe'),
    	    array('iso_code'=>'SN', 'name'=>'Senegal'),
    	    array('iso_code'=>'SC', 'name'=>'Seyşel Adaları'),
    	    array('iso_code'=>'SL', 'name'=>'Sierra Leone'),
    	    array('iso_code'=>'SG', 'name'=>'Singapur'),
    	    array('iso_code'=>'SK', 'name'=>'Slovakya'),
    	    array('iso_code'=>'SI', 'name'=>'Slovenya'),
    	    array('iso_code'=>'SB', 'name'=>'Solomon Adaları'),
    	    array('iso_code'=>'SO', 'name'=>'Somali'),
    	    array('iso_code'=>'LK', 'name'=>'Sri Lanka'),
    	    array('iso_code'=>'SD', 'name'=>'Sudan'),
    	    array('iso_code'=>'SR', 'name'=>'Surinam'),
    	    array('iso_code'=>'SY', 'name'=>'Suriye'),
    	    array('iso_code'=>'SA', 'name'=>'Suudi Arabistan'),
    	    array('iso_code'=>'SJ', 'name'=>'Svalbard ve Jan Mayen'),
    	    array('iso_code'=>'SZ', 'name'=>'Svaziland'),
    	    array('iso_code'=>'RS', 'name'=>'Sırbistan'),
    	    array('iso_code'=>'CS', 'name'=>'Sırbistan-Karadağ'),
    	    array('iso_code'=>'TJ', 'name'=>'Tacikistan'),
    	    array('iso_code'=>'TZ', 'name'=>'Tanzanya'),
    	    array('iso_code'=>'TH', 'name'=>'Tayland'),
    	    array('iso_code'=>'TW', 'name'=>'Tayvan'),
    	    array('iso_code'=>'TG', 'name'=>'Togo'),
    	    array('iso_code'=>'TK', 'name'=>'Tokelau'),
    	    array('iso_code'=>'TO', 'name'=>'Tonga'),
    	    array('iso_code'=>'TT', 'name'=>'Trinidad ve Tobago'),
    	    array('iso_code'=>'TN', 'name'=>'Tunus'),
    	    array('iso_code'=>'TC', 'name'=>'Turks ve Caicos Adaları'),
    	    array('iso_code'=>'TV', 'name'=>'Tuvalu'),
    	    array('iso_code'=>'TM', 'name'=>'Türkmenistan'),
    	    array('iso_code'=>'UG', 'name'=>'Uganda'),
    	    array('iso_code'=>'UA', 'name'=>'Ukrayna'),
    	    array('iso_code'=>'OM', 'name'=>'Umman'),
    	    array('iso_code'=>'UY', 'name'=>'Uruguay'),
    	    array('iso_code'=>'VU', 'name'=>'Vanuatu'),
    	    array('iso_code'=>'VA', 'name'=>'Vatikan'),
    	    array('iso_code'=>'VE', 'name'=>'Venezuela'),
    	    array('iso_code'=>'VN', 'name'=>'Vietnam'),
    	    array('iso_code'=>'WF', 'name'=>'Wallis ve Futuna'),
    	    array('iso_code'=>'YE', 'name'=>'Yemen'),
    	    array('iso_code'=>'NC', 'name'=>'Yeni Kaledonya'),
    	    array('iso_code'=>'NZ', 'name'=>'Yeni Zelanda'),
    	    array('iso_code'=>'GR', 'name'=>'Yunanistan'),
    	    array('iso_code'=>'ZM', 'name'=>'Zambiya'),
    	    array('iso_code'=>'ZW', 'name'=>'Zimbabve'),
    	    array('iso_code'=>'TD', 'name'=>'Çad'),
    	    array('iso_code'=>'CZ', 'name'=>'Çek Cumhuriyeti'),
    	    array('iso_code'=>'CN', 'name'=>'Çin'),
    	    array('iso_code'=>'UZ', 'name'=>'Özbekistan'),
    	    array('iso_code'=>'JO', 'name'=>'Ürdün'),
    	    array('iso_code'=>'VG', 'name'=>'İngiliz Virgin Adaları'),
    	    array('iso_code'=>'IR', 'name'=>'İran'),
    	    array('iso_code'=>'IE', 'name'=>'İrlanda'),
    	    array('iso_code'=>'ES', 'name'=>'İspanya'),
    	    array('iso_code'=>'IL', 'name'=>'İsrail'),
    	    array('iso_code'=>'SE', 'name'=>'İsveç'),
    	    array('iso_code'=>'CH', 'name'=>'İsviçre'),
    	    array('iso_code'=>'IT', 'name'=>'İtalya'),
    	    array('iso_code'=>'IS', 'name'=>'İzlanda'),
    	    array('iso_code'=>'CL', 'name'=>'Şili')
    	);
        Country::truncate();
    	Country::insert($countries);
    }
}
